version: '3.8'

services:
  discovery-service-backend:
    image: discovery-service-backend:latest
    container_name: discovery-service-backend
    ports:
      - "8761:8761"
    environment:
      SERVER_PORT: 8761
    networks:
      - app_network

  api-gateway-backend:
    image: api-gateway-backend:latest
    container_name: api-gateway-backend
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service-backend
    networks:
      - app_network

  environment-service-backend:
    image: environment-service-backend:latest
    container_name: environment-service-backend
    ports: []
    depends_on:
      - DB_environment_testing
      - api-gateway-backend
      - discovery-service-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://DB_environment_testing:5432/environment_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123321
    networks:
      - app_network

  security-service-backend:
    image: security-service-backend:latest
    container_name: security-service-backend
    ports: [ ]
    depends_on:
      - DB_security_testing
      - api-gateway-backend
      - discovery-service-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://DB_security_testing:5432/security_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123321
    networks:
      - app_network

  auth-service-backend:
    image: auth-service-backend:latest
    container_name: auth-service-backend
    ports: [ ]
    depends_on:
      - api-gateway-backend
      - discovery-service-backend
    networks:
      - app_network

  DB_security_testing:
    image: postgres
    restart: always
    container_name: postgres-security-service
    ports:
      - "4336:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: security_service
    volumes:
      - db_data_security:/var/lib/postgresql/data
    networks:
      - app_network

  transport-service-backend:
    image: transport-service-backend:latest
    container_name: transport-service-backend
    ports: [ ]
    depends_on:
      - api-gateway-backend
      - DB_transport_testing
      - discovery-service-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://DB_transport_testing:5432/transport_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123321
    networks:
      - app_network

  DB_transport_testing:
    image: postgres
    restart: always
    container_name: postgres-transport-service
    ports:
      - "4335:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: transport_service
    volumes:
      - db_data_transport:/var/lib/postgresql/data
    networks:
      - app_network

  DB_environment_testing:
    image: postgres
    restart: always
    container_name: postgres-environment-service
    ports:
      - "4334:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: environment_service
    volumes:
      - db_data_environment:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  db_data_transport:
  db_data_environment:
  db_data_security:

networks:
  app_network:
    driver: bridge