version: '3.8'

services:
  discovery-service-backend:
    image: discovery-service-backend:latest
    container_name: discovery-service-backend
    ports:
      - "8761:8761"
    environment:
      SERVER_PORT: 8761
    networks:
      - app_network

  environment-service-backend:
    image: environment-service-backend:latest
    container_name: environment-service-backend
    ports: []
    depends_on:
      - DB_environment_testing
      - discovery-service-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://DB_environment_testing:5432/environment_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123321
    networks:
      - app_network

  DB_environment_testing:
    image: postgres
    restart: always
    container_name: postgres-environment-service
    ports:
      - "4334:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: environment_service
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge